version: "3.8"

services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unifi-controller
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024
    volumes:
      - ./unifi/config:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp
      - 6789:6789
      - 5514:5514/udp
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: unifi_mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: captive_backend
    env_file:
      - .env
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  db_data:
